/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ConvertLazyImport = createFileRoute('/convert')()

// Create/Update Routes

const ConvertLazyRoute = ConvertLazyImport.update({
  path: '/convert',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/convert.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ ConvertLazyRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/convert"
      ]
    },
    "/convert": {
      "filePath": "convert.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
